services:
  issue-org1:
    container_name: issue-org1
    image: ghcr.io/decaf-ts/fabric-weaver:weaver-${FABRIC_VERSION:-2.5.12}-${WEAVER_VERSION:-latest}
    restart: no
    volumes:
      - boot-files1:/boot:rw
      - org-1-server-vol:/weaver/ca/server:rw
    command: >
      bash -c "
      if [ -f /boot/boot-issuer.lock ]; then
        echo 'Org1 TLS boot is already complete. Skipping...';
        exit 0;
      fi;

      node ./weaver/lib/core/cli.cjs issue-ca -d -s --home /weaver/ca/server --port 7010 --tls-enabled --ca-name org-1 --bootstrap-users org-1:org-1-pw --no-tls-profile --csr-cn org-1 --csr-hosts 0.0.0.0,localhost,org-1 --operations-listen-address 127.0.0.1:8001 --tls-certfile /weaver/client/admin/tls-msp/signcerts/cert.pem --tls-keyfile /weaver/client/admin/tls-msp/signcerts/cert.pem &&

      touch /boot/boot-issuer.lock 
      "

  org-1-tls:
    container_name: org-1-tls
    hostname: org-1-tls
    image: ghcr.io/decaf-ts/fabric-weaver:weaver-${FABRIC_VERSION:-2.5.12}-${WEAVER_VERSION:-latest}
    restart: no
    environment:
      - FABRIC_CA_CLIENT_HOME=/weaver/client/admin
      - FABRIC_CA_SERVER_HOME=/weaver/server
    ports:
      - "7000:7000"
    networks:
      org1_network:
    depends_on:
      issue-org1:
        condition: service_completed_successfully
    healthcheck:
      test: bash -c "[ -f /weaver/server/ca-cert.pem ] && curl -s 127.0.0.1:8010/healthz | grep "OK" || exit 1"
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 30s
    volumes:
      - org-1-tls-server-vol:/weaver/server:rw
    command: >
      node ./weaver/lib/core/cli.cjs boot-ca 
      -d 
      -s 
      --home /weaver/server 
      --port 7000 
      --tls-enabled 
      --ca-name org-1-tls 
      --bootstrap-users org-1-tls:org-1-tls-pw 
      --no-ca-profile 
      --csr-cn org-1-tls 
      --csr-hosts 0.0.0.0,localhost,org-1-tls 
      --operations-listen-address 127.0.0.1:8010

volumes:
  boot-files1:
    name: boot-files1

  org-1-tls-server-vol:
    name: org-1-tls-server-vol

  org-1-server-vol:
    name: org-1-server-vol

networks:
  org1_network:
    name: org1_network
    driver: bridge
