services:
  boot-infrastructure:
    container_name: boot-infrastructure
    image: ghcr.io/decaf-ts/fabric-weaver:weaver-${FABRIC_VERSION:-2.5.12}-${WEAVER_VERSION:-latest}
    restart: no
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - boot-files:/boot:rw
    networks:
      org1_network:
      org2_network:
    command: >
      bash -c "
      if [ -f /boot/boot-infrastructure.lock ]; then
        echo 'infrastructure already booted. Skipping...';
        exit 0;
      fi;

      apt-get update &&
      apt-get install -y docker.io &&

      node ./weaver/lib/core/cli.cjs configtxgen \
      --config-path /weaver/general \
      --profile SimpleChannel \
      --channel-id simple-channel \
      --output-block '/weaver/orderer/genesisblock' -s -d &&

      touch /boot/boot-infrastructure.lock
      "

volumes:
  boot-files:
    name: boot-files

networks:
  org1_network:
    external: true
  org2_network:
    external: true
