services:
  boot-infrastructure:
    container_name: boot-infrastructure
    image: ghcr.io/decaf-ts/fabric-weaver:weaver-${FABRIC_VERSION:-2.5.12}-${WEAVER_VERSION:-latest}
    restart: no
    profiles:
      - stage1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - boot-files:/boot:rw
      - org-1-orderer-0-vol:/weaver/client/orderer:rw
      - org-1-peer-0-vol:/weaver/client/peer-1:rw
      - org-2-peer-0-vol:/weaver/client/peer-2:rw
      - ./:/weaver/general:rw
    networks:
      org1_network:
      org2_network:
    command: >
      bash -c "
      if [ -f /boot/boot-infrastructure.lock ]; then
        echo 'infrastructure already booted. Skipping...';
        exit 0;
      fi;

      node ./weaver/lib/core/cli.cjs configtxgen \
      --config-path /weaver/general \
      --profile SimpleChannel \
      --channel-id simple-channel \
      --output-block '/weaver/client/orderer/genesis_block.pb' -s -d &&

      node ./weaver/lib/core/cli.cjs copy -s \
      --origin ./weaver/client/orderer/tls-ca-cert.pem \
      --dest ./weaver/client/peer-2/orderer-tls-ca-cert.pem &&

      node ./weaver/lib/core/cli.cjs copy -s \
      --origin ./weaver/client/peer-2/tls-ca-cert.pem \
      --dest ./weaver/client/peer-1/org-2-tls-ca-cert.pem &&

      touch /boot/boot-infrastructure.lock
      "

  commit-chaincode:
    image: ghcr.io/decaf-ts/fabric-weaver:weaver-${FABRIC_VERSION:-2.5.12}-${WEAVER_VERSION:-latest}
    container_name: commit-chaincode
    restart: no
    profiles:
      - stage2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - boot-files:/boot:rw
      - org-1-peer-0-vol:/weaver/peer:rw
    networks:
      org2_network:
    command: >
      bash -c "
      if [ -f /boot/boot-chaincode.lock ]; then
        echo 'chaincode already booted. Skipping...';
        exit 0;
      fi;

      docker exec org-1-peer-0 node ./weaver/lib/core/cli.cjs commit-chaincode -d -s \
      --orderer-address org-1-orderer-0:7021 \
      --channel-id simple-channel \
      --chaincode-name simple \
      --chaincode-version 1.0 \
      --sequence 1 \
      --enable-tls \
      --tls-ca-cert-file /weaver/peer/tls-ca-cert.pem \
      --peer-addresses org-1-peer-0:7031,org-2-peer-0:7032
      --peer-root-tls ./weaver/peer/tls-ca-cert.pem,./weaver/peer/org-2-tls-ca-cert.pem &&

      touch /boot/boot-chaincode.lock
      "

volumes:
  boot-files:
    name: boot-files

  org-1-orderer-0-vol:
    external: true

  org-1-peer-0-vol:
    external: true

  org-2-orderer-0-vol:
    external: true

  org-2-peer-0-vol:
    external: true

networks:
  org1_network:
    external: true
  org2_network:
    external: true
