services:
  org-1:
    container_name: org-1
    hostname: org-1
    image: ghcr.io/decaf-ts/fabric-weaver:weaver-${FABRIC_VERSION:-2.5.12}-${WEAVER_VERSION:-latest}
    restart: no
    ports:
      - "7010:7010"
    healthcheck:
      test: bash -c "[ -f /weaver/server/ca-cert.pem ] && curl -s 127.0.0.1:8010/healthz | grep "OK" || exit 1"
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 30s
    command: >
      node ./weaver/lib/core/cli.cjs docker:boot-ca
        -h /weaver/server
        -p 7010
        -d
        -b admin:adminpw
        -l fatal
        --ca-name org-1
        --operations-address 127.0.0.1:8010
        --metrics-address 127.0.0.1:9010
