services:
  org-1:
    container_name: org-1
    hostname: org-1
    image: ghcr.io/decaf-ts/fabric-weaver:weaver-${FABRIC_VERSION:-2.5.12}-${WEAVER_VERSION:-latest}
    restart: no
    ports:
      - "7010:7010"
    healthcheck:
      test: bash -c "[ -f /weaver/server/ca-cert.pem ] && curl -s 127.0.0.1:8010/healthz | grep "OK" || exit 1"
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 30s
    command: >
      node ./weaver/lib/core/cli.cjs docker:boot-ca
        --home /weaver/server
        --port 7010
        --debug
        --bootstrap-user admin:adminpw
        --ca-name org-1
        --operations-address 127.0.0.1:8010
        --metrics-address 127.0.0.1:9010
        --no-tls

  org-2:
    container_name: org-2
    hostname: org-2
    image: ghcr.io/decaf-ts/fabric-weaver:weaver-${FABRIC_VERSION:-2.5.12}-${WEAVER_VERSION:-latest}
    restart: no
    ports:
      - "7011:7011"
    healthcheck:
      test: bash -c "[ -f /weaver/server/ca-cert.pem ] && curl -s 127.0.0.1:8010/healthz | grep "OK" || exit 1"
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 30s
    command: >
      node ./weaver/lib/core/cli.cjs docker:boot-ca
        --home /weaver/server
        --port 7010
        --debug
        --bootstrap-user admin:adminpw
        --ca-name org-2
        --operations-address 127.0.0.1:8010
        --metrics-address 127.0.0.1:9010
        --no-tls

  test-1:
    container_name: test-1
    hostname: test-1
    image: ghcr.io/decaf-ts/fabric-weaver:weaver-${FABRIC_VERSION:-2.5.12}-${WEAVER_VERSION:-latest}
    restart: no
    command: >
      node ./weaver/lib/core/cli.cjs docker:client-register
        --url https://somedomain:7000
        --id-name myuser
        --id-secret mypass
        --tls-certfiles /somelocation/somfile.pem
        --mspdir /somelocation/mspdir
        -d

  test-2:
    container_name: test-2
    hostname: test-2
    image: ghcr.io/decaf-ts/fabric-weaver:weaver-${FABRIC_VERSION:-2.5.12}-${WEAVER_VERSION:-latest}
    restart: no
    command: >
      node ./weaver/lib/core/cli.cjs docker:client-enroll
        --url https://myuser:mypassword@somedomain:7000
        --tls-certfiles /somelocation/somfile.pem
        --mspdir /somelocation/mspdir
        -d
