services:
  org-1-boot:
    container_name: org-1-boot
    hostname: org-1-boot
    image: ghcr.io/decaf-ts/fabric-weaver:weaver-${FABRIC_VERSION:-2.5.12}-${WEAVER_VERSION:-latest}
    restart: no
    volumes:
      - org1-vol:/weaver/server:rw
    command: >
      node ./weaver/lib/core/cli.cjs docker:issue-ca
        --home /weaver/server
        --port 7012
        --debug
        --bootstrap-user admin:adminpw
        --ca-name org-1
        --operations-address 127.0.0.1:8010
        --metrics-address 127.0.0.1:9010
        --no-tls

  org-2-boot:
    container_name: org-2-boot
    hostname: org-2-boot
    image: ghcr.io/decaf-ts/fabric-weaver:weaver-${FABRIC_VERSION:-2.5.12}-${WEAVER_VERSION:-latest}
    restart: no
    volumes:
      - org2-vol:/weaver/server:rw
    command: >
      node ./weaver/lib/core/cli.cjs docker:issue-ca
        --home /weaver/server
        --port 7013
        --debug
        --bootstrap-user admin:adminpw
        --ca-name org-2
        --operations-address 127.0.0.1:8010
        --metrics-address 127.0.0.1:9010
        --no-tls

  org-1:
    container_name: org-1
    image: hyperledger/fabric-ca:1.5.15
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=org-1
    ports:
      - 7012:7012
    working_dir: /etc/hyperledger/fabric-ca-server
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    depends_on:
      org-1-boot:
        condition: service_completed_successfully
    healthcheck:
      test: bash -c "[ -f /etc/hyperledger/fabric-ca-server/ca-cert.pem ]"
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 30s
    volumes:
      - org1-vol:/etc/hyperledger/fabric-ca-server/

  org-2:
    container_name: org-2
    image: hyperledger/fabric-ca:1.5.15
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=org-2
    ports:
      - 7013:7013
    working_dir: /etc/hyperledger/fabric-ca-server
    depends_on:
      org-2-boot:
        condition: service_completed_successfully
    healthcheck:
      test: bash -c "[ -f /etc/hyperledger/fabric-ca-server/ca-cert.pem ]"
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 30s
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - org2-vol:/etc/hyperledger/fabric-ca-server/

volumes:
  org1-vol:
  org2-vol:
