services:
  org-1-tls:
    container_name: org-1-tls
    hostname: org-1-tls
    image: ghcr.io/decaf-ts/fabric-weaver:weaver-${FABRIC_VERSION:-2.5.12}-${WEAVER_VERSION:-latest}
    restart: no
    environment:
      - FABRIC_CA_CLIENT_HOME=/weaver/client/admin
      - FABRIC_CA_SERVER_HOME=/weaver/server
      - FABRIC_CA_CLIENT_TLS_CERTFILES=/weaver/server/ca-cert.pem
    ports:
      - "7001:7001"
    networks:
      org1_network:
    healthcheck:
      test: bash -c "[ -f /weaver/server/ca-cert.pem ] && curl -s 127.0.0.1:8010/healthz | grep "OK" || exit 1"
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 30s
    volumes:
      - org-1-tls-server-vol:/weaver/server:rw
      - org-1-tls-client-vol:/weaver/client:rw
    command: >
      node ./weaver/lib/core/cli.cjs boot-ca 
      -d 
      -s 
      --home /weaver/server 
      --port 7001 
      --tls-enabled 
      --ca-name org-1-tls 
      --bootstrap-users org-1-tls-admin:org-1-tls-admin-pw 
      --no-ca-profile 
      --csr-cn org-1-tls 
      --csr-hosts 0.0.0.0,localhost,org-1-tls 
      --operations-listen-address 127.0.0.1:8010

  boot-org-1-tls:
    container_name: boot-org-1-tls
    image: ghcr.io/decaf-ts/fabric-weaver:weaver-${FABRIC_VERSION:-2.5.12}-${WEAVER_VERSION:-latest}
    restart: no
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - boot-files1:/boot:rw
      - org-1-client-vol:/weaver/client:rw
      - org-1-tls-server-vol:/weaver/server:rw
    depends_on:
      org-1-tls:
        condition: service_healthy
    networks:
      org1_network:
    command: >
      bash -c "
      if [ -f /boot/boot-org-1-tls.lock ]; then
        echo 'Org 1 TLS already booted. Skipping...';
        exit 0;
      fi;

      apt-get update &&
      apt-get install -y docker.io &&

      docker exec org-1-tls node ./weaver/lib/core/cli.cjs client-enrollment \
      -d --url https://org-1-tls-admin:org-1-tls-admin-pw@org-1-tls:7001 \
      --command enroll && 

      docker exec org-1-tls node ./weaver/lib/core/cli.cjs client-enrollment \
      -d -s --command register \
      --url https://org-1-tls:7001 \
      --id-name org-1-admin \
      --id-secret org-1-admin-pw \
      --tls-certfiles /weaver/server/ca-cert.pem \
      --mspdir /weaver/client/admin/msp &&

      docker exec org-1-tls node ./weaver/lib/core/cli.cjs client-enrollment \
      -d -s --command register \
      --url https://org-1-tls:7001 \
      --id-name org-1-orderer-0-admin \
      --id-secret org-1-orderer-0-admin-pw \
      --tls-certfiles /weaver/server/ca-cert.pem \
      --mspdir /weaver/client/admin/msp &&

      docker exec org-1-tls node ./weaver/lib/core/cli.cjs client-enrollment \
      -d -s --command register \
      --url https://org-1-tls:7001 \
      --id-name org-1-orderer-0 \
      --id-secret org-1-orderer-0-pw \
      --tls-certfiles /weaver/server/ca-cert.pem \
      --mspdir /weaver/client/admin/msp &&

      docker exec org-1-tls node ./weaver/lib/core/cli.cjs client-enrollment \
      -d -s --command register \
      --url https://org-1-tls:7001 \
      --id-name org-1-peer-0-admin \
      --id-secret org-1-peer-0-admin-pw \
      --tls-certfiles /weaver/server/ca-cert.pem \
      --mspdir /weaver/client/admin/msp &&

      docker exec org-1-tls node ./weaver/lib/core/cli.cjs client-enrollment \
      -d -s --command register \
      --url https://org-1-tls:7001 \
      --id-name org-1-peer-0 \
      --id-secret org-1-peer-0 \
      --tls-certfiles /weaver/server/ca-cert.pem \
      --mspdir /weaver/client/admin/msp &&

      node ./weaver/lib/core/cli.cjs copy -s \
      --origin ./weaver/server/ca-cert.pem \
      --dest ./weaver/client/tls.pem &&

      node ./weaver/lib/core/cli.cjs client-enrollment \
      -d -s --command enroll \
      --url https://org-1-admin:org-1-admin-pw@org-1-tls:7001 \
      --mspdir /weaver/client/admin/tls-msp \
      --enrollment-profile tls  \
      --csr-hosts 0.0.0.0,localhost,org-1 \
      --tls-certfiles /weaver/client/tls.pem \
      --rename-key

      touch /boot/boot-org-1-tls.lock 
      "

  org-1:
    container_name: org-1
    hostname: org-1
    image: ghcr.io/decaf-ts/fabric-weaver:weaver-${FABRIC_VERSION:-2.5.12}-${WEAVER_VERSION:-latest}
    restart: no
    environment:
      - FABRIC_CA_CLIENT_HOME=/weaver/client/admin
      - FABRIC_CA_SERVER_HOME=/weaver/server
      - FABRIC_CA_CLIENT_TLS_CERTFILES=/weaver/client/tls.pem
    ports:
      - "7011:7011"
    networks:
      org1_network:
    depends_on:
      boot-org-1-tls:
        condition: service_completed_successfully
    healthcheck:
      test: bash -c "[ -f /weaver/server/ca-cert.pem ] && curl -s 127.0.0.1:8010/healthz | grep "OK" || exit 1"
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 30s
    volumes:
      - org-1-server-vol:/weaver/server:rw
      - org-1-client-vol:/weaver/client:rw
    command: >
      node ./weaver/lib/core/cli.cjs boot-ca 
      -d 
      -s 
      --home /weaver/server 
      --port 7011 
      --tls-enabled 
      --ca-name org-1 
      --bootstrap-users org-1-admin:org-1-admin-pw 
      --no-tls-profile
      --csr-cn org-1 
      --csr-hosts 0.0.0.0,localhost,org-1 
      --operations-listen-address 127.0.0.1:8010
      --tls-certfile /weaver/client/admin/tls-msp/signcerts/cert.pem
      --tls-keyfile /weaver/client/admin/tls-msp/keystore/key.pem

  boot-org-1:
    container_name: boot-org-1
    image: ghcr.io/decaf-ts/fabric-weaver:weaver-${FABRIC_VERSION:-2.5.12}-${WEAVER_VERSION:-latest}
    restart: no
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - boot-files1:/boot:rw
    depends_on:
      org-1:
        condition: service_healthy
    networks:
      org1_network:
    command: >
      bash -c "
      if [ -f /boot/boot-org-1.lock ]; then
        echo 'Org 1 already booted. Skipping...';
        exit 0;
      fi;

      apt-get update &&
      apt-get install -y docker.io &&

      docker exec org-1 node ./weaver/lib/core/cli.cjs client-enrollment \
      -d --command enroll \
      --url https://org-1-admin:org-1-admin-pw@org-1:7011 \
      --tls-certfiles /weaver/client/tls.pem \
      --mspdir /weaver/client/admin/msp &&

      docker exec org-1 node ./weaver/lib/core/cli.cjs client-enrollment \
      -d -s --command register \
      --url https://org-1:7011 \
      --id-name org-1-orderer-0-admin \
      --id-secret org-1-orderer-0-admin-pw \
      --id-type admin \
      --tls-certfiles /weaver/client/tls.pem \
      --mspdir /weaver/client/admin/msp &&

      docker exec org-1 node ./weaver/lib/core/cli.cjs client-enrollment \
      -d -s --command enroll \
      --url https://org-1-orderer-0-admin:org-1-orderer-0-admin-pw@org-1:7011 \
      --tls-certfiles /weaver/client/tls.pem \
      --mspdir /weaver/client/orderers/orderer-0/client/msp \
      --csr-hosts org-1-orderer-0,0.0.0.0,localhost \
      --home /weaver/client/orderers/orderer-0/client &&

      docker exec org-1 node ./weaver/lib/core/cli.cjs client-enrollment \
      -d -s --command enroll \
      --url https://org-1-orderer-0-admin:org-1-orderer-0-admin-pw@org-1-tls:7001 \
      --enrollment-profile tls \
      --csr-hosts org-1-orderer-0,0.0.0.0,localhost \
      --tls-certfiles /weaver/client/tls.pem \
      --mspdir /weaver/client/orderers/orderer-0/client/tls-msp \
      --home /weaver/client/orderers/orderer-0/client \
      --rename-key &&

      docker exec org-1 node ./weaver/lib/core/cli.cjs client-enrollment \
      -d -s --command register \
      --url https://org-1:7011 \
      --id-name org-1-orderer-0 \
      --id-secret org-1-orderer-0-pw \
      --id-type orderer \
      --tls-certfiles /weaver/client/tls.pem \
      --mspdir /weaver/client/admin/msp &&

      docker exec org-1 node ./weaver/lib/core/cli.cjs client-enrollment \
      -d -s --command enroll \
      --url https://org-1-orderer-0:org-1-orderer-0-pw@org-1:7011 \
      --tls-certfiles /weaver/client/tls.pem \
      --mspdir /weaver/client/orderers/orderer-0/msp \
      --csr-hosts org-1-orderer-0,0.0.0.0,localhost \
      --home /weaver/client/orderers/orderer-0 &&

      docker exec org-1 node ./weaver/lib/core/cli.cjs client-enrollment \
      -d -s --command enroll \
      --url https://org-1-orderer-0:org-1-orderer-0-pw@org-1-tls:7001 \
      --enrollment-profile tls \
      --csr-hosts org-1-orderer-0,0.0.0.0,localhost \
      --tls-certfiles /weaver/client/tls.pem \
      --mspdir /weaver/client/orderers/orderer-0/tls-msp \
      --home /weaver/client/orderers/orderer-0/tls-msp \
      --rename-key &&

      touch /boot/boot-org-1.lock 
      "

# orderer admin "id.attrs":"\"hf.Registrar.Roles=admin,client,user,orderer\",\"hf.Registrar.Attributes=*\",\"hf.Revoker=true\",\"hf.GenCRL=true\",\"admin=true:ecert\",\"abac.init=true:ecert\"",

volumes:
  boot-files1:
    name: boot-files1

  org-1-tls-server-vol:
    name: org-1-tls-server-vol
  org-1-tls-client-vol:
    name: org-1-tls-client-vol

  org-1-server-vol:
    name: org-1-server-vol
  org-1-client-vol:
    name: org-1-client-vol

networks:
  org1_network:
    name: org1_network
    driver: bridge
