services:
  boot-infrastructure:
    container_name: boot-infrastructure
    image: ghcr.io/decaf-ts/fabric-weaver:weaver-${FABRIC_VERSION:-2.5.12}-${WEAVER_VERSION:-latest}
    restart: no
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - boot-files:/boot:rw
      - org-1-orderer-0-vol:/weaver/client/orderer:rw
      - org-1-peer-0-vol:/weaver/client/peer-1:rw
      - org-2-peer-0-vol:/weaver/client/peer-2:rw
      - ./:/weaver/general:rw
    networks:
      org1_network:
      org2_network:
    command: >
      bash -c "
      if [ -f /boot/boot-infrastructure.lock ]; then
        echo 'infrastructure already booted. Skipping...';
        exit 0;
      fi;

      node ./weaver/lib/core/cli.cjs configtxgen \
      --config-path /weaver/general \
      --profile SimpleChannel \
      --channel-id simple-channel \
      --output-block '/weaver/client/orderer/genesis_block.pb' -s -d &&

      node ./weaver/lib/core/cli.cjs copy -s \
      --origin ./weaver/client/orderer/tls-ca-cert.pem \
      --dest ./weaver/client/peer-2/orderer-tls-ca-cert.pem &&

      touch /boot/boot-infrastructure.lock
      "

volumes:
  boot-files:
    name: boot-files

  org-1-orderer-0-vol:
    external: true

  org-1-peer-0-vol:
    external: true

  org-2-orderer-0-vol:
    external: true

  org-2-peer-0-vol:
    external: true

networks:
  org1_network:
    external: true
  org2_network:
    external: true
