name: "Publish on Release"

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        node-version: [22]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/
          # Cache dependencies (npm)
      - name: Cache dependencies
        id: cache-npm
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            node_modules
          key: deps-${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            deps-${{ runner.os }}-${{ matrix.node-version }}-
      - run: npm ci
      - run: npm run setup
      - name: Cache Build
        id: cache-build
        uses: actions/cache@v4
        with:
          path: |
            lib
            dist
          key: build-${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            build-${{ runner.os }}-${{ matrix.node-version }}-

      - if: ${{ steps.cache-build.outputs.cache-hit != 'true' }}
        run: npm run build:prod # Replace with your build command

      - name: Build Docker image
        run: npm run docker:build
      - run: npm run test:all
      - run: npm publish --access public
        env:
          GITHUB_TOKEN: ${{ secrets.CONSECUTIVE_ACTION_TRIGGER }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag and Push Docker Image
        run: npm run docker:publish
